version: '3'

services:
    bot:
        build: 
            context: bot  
        environment:
            BOT_SERVER_URL: "http://bot:8090"
        ports:
            - 8090:8090
        depends_on:
            - tarantool

    tarantool:
        image: tarantool/tarantool:2.8
        ports:
          - "3301:3301"
        volumes:
          - ./tarantool:/var/lib/tarantool
        command: tarantool tarantool /var/lib/tarantool/init.lua
